add wave -position insertpoint  \
sim:/alureservationstations/reset \
sim:/alureservationstations/clk \
sim:/alureservationstations/issue \
sim:/alureservationstations/validAlu \
sim:/alureservationstations/validMem \
sim:/alureservationstations/opcode \
sim:/alureservationstations/tag1 \
sim:/alureservationstations/valid1 \
sim:/alureservationstations/tag2 \
sim:/alureservationstations/valid2 \
sim:/alureservationstations/issueDestName \
sim:/alureservationstations/lastExcutedAluDestName \
sim:/alureservationstations/lastExcutedAluDestNameValue \
sim:/alureservationstations/lastExcutedMemDestName \
sim:/alureservationstations/lastExcutedMemDestNameValue \
sim:/alureservationstations/resets \
sim:/alureservationstations/enablesOpcode \
sim:/alureservationstations/enablesTag1 \
sim:/alureservationstations/enablesValid1 \
sim:/alureservationstations/enablesTag2 \
sim:/alureservationstations/enablesValid2 \
sim:/alureservationstations/enablesDestName \
sim:/alureservationstations/busies \
sim:/alureservationstations/readies \
sim:/alureservationstations/outEnables \
sim:/alureservationstations/aluOp \
sim:/alureservationstations/op1 \
sim:/alureservationstations/op2 \
sim:/alureservationstations/valid \
sim:/alureservationstations/full \
